/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qxrxvimogjyhbtikrhqx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4cnh2aW1vZ2p5aGJ0aWtyaHF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyODg2MTMsImV4cCI6MjA4Nzg2NDYxM30.63eQdkRoUy-zDjXX-lOSnYUF4XJ8Dye-vpGecJO6Taw"